### ISSUE TITLE
Do we have provide run_quoref.py

### ISSUE THREAD

**Issue by Junzx** [ShannonAI/CorefQA#7]
Hi. Thanks for your contribution. It's a real meaningful work.

While i'm trying to run the project, I found it didn't seem to provide the `run_quoref.py` mentioned in [./script/model/quoref_tpu.sh](https://github.com/ShannonAI/CorefQA/blob/master/scripts/models/quoref_tpu.sh)? Or maybe i'm carelessly misunderstand the documentation?

Thanks

**Comment by ghost** [comment]
![Screen Shot 2020-08-04 at 4 42 32 PM](https://user-images.githubusercontent.com/29752751/89273002-8ccb3e80-d671-11ea-976d-976f70db076e.png)

**Comment by Junzx** [comment]
Thanks for the reply. But I still can't find the file `run_quoref.py` in `./CorefQA/run/`, my screenshot is like this: 

![image](https://user-images.githubusercontent.com/31405129/89276929-c94d6900-d676-11ea-912a-e5bd0a260925.png)


and I tried to search like this :

![image](https://user-images.githubusercontent.com/31405129/89277199-14677c00-d677-11ea-8ee3-c1a405dd9d36.png)

or can I jump the step "finetune in Quoref dataset" with [quoref_tpu.sh](https://github.com/ShannonAI/CorefQA/blob/master/scripts/models/quoref_tpu.sh)?

**Comment by robinsingh1** [comment]
@Junzx @ghost did this issue get resolved ? I'm seeing it marked as closed but not seeing where the run_quoref.py file in the quoref_tpu.sh script is in the code base?

**Comment by Junzx** [comment]
@robinsingh1 
no. I haven't found the run_quoref.py and I jump this step.
I faild to run this repo because i don't have tpu and my gpu is not enough(or maybe I made other mistakes...
